---
abstract: 'An N-ary tree'
author:
  - 'Sean M. Burke <sburke@cpan.org>'
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.131560'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tree-DAG_Node
provides:
  Tree::DAG_Node:
    file: lib/Tree/DAG_Node.pm
    version: 1.14
requires:
  File::Temp: 0.2301
  Path::Tiny: 0.025
  Perl6::Slurp: 0.051003
  open: 0
  perl: v5.8.1
  strict: 0
  warnings: 0
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 1.14
